### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by tunopendientes** [WadeGulbrandsen/moodle-docker#1]
Hi, thanks for your work. 

To me is unable to configure the email server to send emails. I tried all the ways and no results at all. 

Anything to suggest?

Thanks

**Comment by WadeGulbrandsen** [comment]
Hello,

There's no email server built into this image. You need to configure Moodle to send mail with an external email server. I've tested with Microsoft Exchange, Postfix in a Docker container, Office 365, Gmail, and Mailgun.

Moodle's documentation for that is here: https://docs.moodle.org/311/en/Mail_configuration

You might also find the eMail Test plugin helpful in troubleshooting: https://moodle.org/plugins/local_mailtest

Hope that helps.

**Comment by tunopendientes** [comment]
Thanks for your answer. I know that I have to configure my smtp email server. I do but with the plugin you sent says "Moodle could not communicate with your mail server."

Did you try to test it?

Thanks again

**Comment by WadeGulbrandsen** [comment]
I have tested it with several email servers. The plugin just gives you more info when testing your config.

From your error message it looks like a networking issue. You can test the connection outside of Moodle by doing a simple telnet command.

```bash
telnet your.email.server port
```

For example I use Mailgun so in Moodle I'm using `smtp.mailgun.org:587` for my SMTP host.

```bash
telnet smtp.mailgun.org 587
Trying 34.224.137.116...
Connected to smtp.mailgun.org.
Escape character is '^]'.
220 Mailgun Influx ready
```

The `Trying 34.224.137.116...` lets me know that DNS worked to resolve the address. `Connected to smtp.mailgun.org` lets me know that something is listening on port 587.

I'd recommend doing that first on the Docker host to make sure it works outside the container and then do it again inside the container. To get a prompt inside the container you can run:

```bash
docker exec -it <YOUR_CONTAINER> bash
```
Once inside the container you'll need to install telnet before you can run it:

```bash
apt update
apt install telnet
telnet your.mail.server port
```

**Comment by tunopendientes** [comment]
Hi again and thanks a lot.

I did it and there is no problem. Here is my telnet

Trying 46.251.251.78...
Connected to smtp.letsjoin.es.
Escape character is '^]'.
220 smtp.letsjoin.es ESMTP Haraka/2.8.28 ready

I have no firewall. I am IT Ingenier- I understand eveything you say and tried everything. Somethng happens. But it's OK.

I have my own docker poste email working without any problem at all. I user it in other apps but here something happens.

I do not find the problem.

Thanks again

**Comment by tunopendientes** [comment]
Hi again. 

I solved it! The only way was to install postfix server inside the container and now it works.
